# Generated by Django 2.2.2 on 2019-07-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dia_semana',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
