# Generated by Django 2.1.5 on 2019-05-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('TN', 'Técnico'), ('TG', 'Tecnologia'), ('BA', 'Bacharel'), ('LI', 'Licenciatura'), ('ME', 'Mestrado')], max_length=2),
        ),
    ]
