# Generated by Django 2.2.2 on 2019-07-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_auto_20190702_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('SEGUNDA', 'Segunda Feira'), ('TERCA', 'Terça Feira'), ('QUARTA', 'Quarta Feira'), ('QUINTA', 'Quinta Feira'), ('SEXTA', 'Sexta Feira')], max_length=7, null=True),
        ),
    ]
