# Generated by Django 2.1.5 on 2019-05-19 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_auto_20190517_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='matriculaCurso',
            new_name='matricula_curso',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='cargaHoraria',
            new_name='carga_horaria',
        ),
        migrations.AlterField(
            model_name='matriculadisciplinar',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricula_disciplinar', to='comum.Aluno'),
        ),
        migrations.AlterField(
            model_name='matriculadisciplinar',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricula_disciplinar', to='comum.Turma'),
        ),
    ]
