# Generated by Django 2.0 on 2019-05-24 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0003_auto_20190519_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='ministrantes',
            field=models.ManyToManyField(through='comum.Turma', to='comum.Professor'),
        ),
        migrations.AddField(
            model_name='matriculadisciplinar',
            name='matricula',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(through='comum.MatriculaDisciplinar', to='comum.Aluno'),
        ),
        migrations.AddField(
            model_name='turma',
            name='especificacao_disciplina',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
