# Generated by Django 2.0 on 2019-06-26 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencia', to='comum.Turma')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencia', to='comum.Horario')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('peso', models.IntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro', to='comum.MatriculaDisciplinar')),
                ('frequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro', to='frequencia.Frequencia')),
            ],
        ),
        migrations.AddField(
            model_name='frequencia',
            name='registros',
            field=models.ManyToManyField(through='frequencia.Registro', to='comum.MatriculaDisciplinar'),
        ),
    ]
