# Generated by Django 2.1.5 on 2019-05-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horarios', '0001_initial'),
        ('comum', '0002_auto_20190517_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencia', to='comum.Turma')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencia', to='horarios.Horario')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('peso', models.IntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro', to='comum.MatriculaDisciplinar')),
                ('frequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro', to='frequencia.Frequencia')),
            ],
        ),
    ]
