# Generated by Django 2.0 on 2019-06-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0004_auto_20190611_0000'),
        ('frequencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='registros',
            field=models.ManyToManyField(through='frequencia.Registro', to='comum.MatriculaDisciplinar'),
        ),
    ]
