# Generated by Django 2.1.5 on 2019-05-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comum', '0002_auto_20190517_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSemana', models.CharField(choices=[('SEGUNDA', 'Segunda Feira'), ('TERCA', 'Terça Feira'), ('QUARTA', 'Quarta Feira'), ('QUINTA', 'Quinta Feira'), ('SEXTA', 'Sexta Feira')], max_length=7)),
                ('horarioInicio', models.TimeField()),
                ('horaFim', models.TimeField()),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='comum.Turma')),
            ],
        ),
    ]
