# Generated by Django 2.0 on 2019-05-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0004_auto_20190524_1518'),
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='diaSemana',
            new_name='dia_semana',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='horaFim',
            new_name='hora_fim',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='horarioInicio',
            new_name='hora_inicio',
        ),
        migrations.AddField(
            model_name='ausencia',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencia', to='horarios.Horario'),
        ),
        migrations.AddField(
            model_name='ausencia',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencia', to='comum.Professor'),
        ),
        migrations.AddField(
            model_name='ausencia',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencia', to='comum.Turma'),
        ),
    ]
